version: 2.0

jobs:
  build:
    docker:
      # specify the version
      - image: ssimpson/hugo:latest

    steps:
      # get the code
      - checkout

      # update the theme submodule
      - run: git submodule update --init themes/poopshow

      - run: hugo version
      #run hugo to generate with theme
      - run: hugo

      - persist_to_workspace:
          root: /root/project
          paths:
          - public

  deploy:
    docker:
      - image: google/cloud-sdk

    steps:
      - attach_workspace:
          at: /tmp/project

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          
      - run: gsutil -m cp -r /tmp/project/public/* gs://blog.ke5eo.com/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build